services:
  cache-server:
    image: redis
    ports:
      - "6379:6379" # 현재 인스턴스(PC)에 6379으로 접근한다면 설치되어 있는 Docker Engine가 6379포트인 컨테이너로 연결
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10
    volumes:
      - redis_data:/data # 명명된 볼륨(앞에 경로 ./ 안붙임), 도커 내부에서 확인 가능, 로컬에 파일 생성 안됨 (가상의 리눅스 공간에 저장)

  db-server:
    image: mysql:8.0
    command: --ngram_token_size=1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1243   # 루트 비밀번호
      MYSQL_DATABASE: gmdb        # 1. 'gmdb'라는 데이터베이스라고 설정 (없다면 생성)
      MYSQL_USER: admin2          # 2. 'admin2'라는 유저 설정 (없다면 생성)
      MYSQL_PASSWORD: 1243        # 3. 'admin2'의 비밀번호 설정 (없다면 생성)
    volumes:
      - mysql_data:/var/lib/mysql

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      # 기본 식별자
      KAFKA_NODE_ID: 1

      # KRaft 모드 역할 (이게 없으면 주키퍼 찾음)
      KAFKA_PROCESS_ROLES: broker,controller

      # 네트워크
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

      # 투표자 설정 (필수 - KRaft 리더 선출용)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      # 싱글 노드 강제 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # 메모리 제한
      KAFKA_HEAP_OPTS: "-Xmx400m -Xms400m"

    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  redis_data:
  mysql_data:
  kafka_data:
