services: # local 작업 용 compose.yml
  cache-server:
    image: redis
    ports:
      - "6379:6379" # 현재 인스턴스(PC)에 6379으로 접근한다면 설치되어 있는 Docker Engine가 6379포트인 컨테이너로 연결
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10
    volumes:
      - redis_data:/data # 명명된 볼륨(앞에 경로 ./ 안붙임), 도커 내부에서 확인 가능, 로컬에 파일 생성 안됨 (가상의 리눅스 공간에 저장)

  db-server:
    image: mysql:8.0
    command: --ngram_token_size=1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1243   # 루트 비밀번호
      MYSQL_DATABASE: gmdb        # 1. 'gmdb'라는 데이터베이스라고 설정 (없다면 생성)
      MYSQL_USER: admin2          # 2. 'admin2'라는 유저 설정 (없다면 생성)
      MYSQL_PASSWORD: 1243        # 3. 'admin2'의 비밀번호 설정 (없다면 생성)
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redis_data:
  mysql_data:
