services:    # 컨테이너를 정의하는 서비스라고 선언

  server1:
    container_name: server1 # 컨테이너 이름을 지정
    image: 291234479386.dkr.ecr.ap-northeast-2.amazonaws.com/gallaemallae:latest # ECR 이미지 경로/이미지명:태그
    ports:
      - 8081:8080
    volumes:
      # 애플리케이션 로그를 호스트에 저장 (명명된 볼륨)
      - /home/ubuntu/docker/server1/logs:/app/logs
    networks:
      - my-network

  server2:
    container_name: server2
    image: 291234479386.dkr.ecr.ap-northeast-2.amazonaws.com/gallaemallae:latest # ECR 이미지 경로/이미지명:태그
    ports:
      - 8082:8080
    volumes:
      # 애플리케이션 로그를 호스트에 저장
      - /home/ubuntu/docker/server2/logs:/app/logs
    networks:
      - my-network

# 사용할 네트워크를 명시적으로 정의
networks:
  my-network:
    driver: bridge
